import React, { useState, useEffect } from 'react';
import { Calendar as CalendarIcon, Clock, Book, Plus, Trash2, Check, RefreshCw, CalendarDays } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { apiService } from '../api/apiService';
import { useToast } from '../context/ToastContext';
import { Skeleton } from '../components/ui/Skeleton';
import './pages.css';

const Schedule = () => {
  const toast = useToast();
  const [schedulePlan, setSchedulePlan] = useState(null);
  const [formData, setFormData] = useState({
    examDate: '',
    studyHoursPerDay: 4,
    subjects: [{ name: '', weight: 'High' }]
  });
  const [loading, setLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedDayTasks, setSelectedDayTasks] = useState([]);
  const [selectedDateStr, setSelectedDateStr] = useState('');

  // Reschedule dialog states
  const [reschedulingTask, setReschedulingTask] = useState(null);
  const [newDate, setNewDate] = useState('');

  const loadSchedule = async () => {
    setLoading(true);
    try {
      const plan = await apiService.schedule.get();
      if (plan && plan.tasks && plan.tasks.length > 0) {
        setSchedulePlan(plan);
        // Default to showing first task's date tasks
        const firstTaskDate = plan.tasks[0]?.date;
        if (firstTaskDate) {
          showTasksForDate(plan.tasks, firstTaskDate);
        }
      }
    } catch {
      toast.error('Failed to load study planner.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSchedule();
  }, []);

  const handleSubjectChange = (index, field, value) => {
    const updated = [...formData.subjects];
    updated[index][field] = value;
    setFormData({ ...formData, subjects: updated });
  };

  const addSubject = () =>
    setFormData({ ...formData, subjects: [...formData.subjects, { name: '', weight: 'Medium' }] });

  const removeSubject = (index) =>
    setFormData({ ...formData, subjects: formData.subjects.filter((_, i) => i !== index) });

  const handleGenerate = async (e) => {
    e.preventDefault();
    setIsGenerating(true);
    try {
      const res = await apiService.schedule.generate(formData);
      if (res.success) {
        toast.success('Study planner generated by AI!');
        setSchedulePlan(res.plan);
        if (res.plan.tasks.length > 0) {
          showTasksForDate(res.plan.tasks, res.plan.tasks[0].date);
        }
      }
    } catch {
      toast.error('Schedule generation failed.');
    } finally {
      setIsGenerating(false);
    }
  };

  const showTasksForDate = (tasks, dateStr) => {
    const dayTasks = tasks.filter(t => t.date === dateStr);
    setSelectedDayTasks(dayTasks);
    setSelectedDateStr(dateStr);
  };

  const handleToggleTask = async (taskId) => {
    try {
      const res = await apiService.schedule.toggleTask(taskId);
      if (res.success) {
        setSchedulePlan(res.plan);
        showTasksForDate(res.plan.tasks, selectedDateStr);
        toast.success('Task status updated.');
      }
    } catch {
      toast.error('Failed to update task.');
    }
  };

  const startReschedule = (task) => {
    setReschedulingTask(task);
    setNewDate(task.date);
  };

  const handleRescheduleSubmit = async () => {
    if (!newDate) return;
    try {
      const res = await apiService.schedule.rescheduleTask(reschedulingTask.id, newDate);
      if (res.success) {
        setSchedulePlan(res.plan);
        // Refresh selected date tasks to reflect the move
        showTasksForDate(res.plan.tasks, selectedDateStr);
        setReschedulingTask(null);
        toast.success('Task rescheduled successfully.');
      }
    } catch {
      toast.error('Failed to reschedule task.');
    }
  };

  const weekDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  // Calculate calendar grid dates. We'll generate a grid of 14 days representing study days.
  const getCalendarDays = () => {
    if (!schedulePlan || !schedulePlan.tasks) return [];
    
    // Group tasks by date
    const dateMap = {};
    schedulePlan.tasks.forEach(t => {
      if (!dateMap[t.date]) dateMap[t.date] = [];
      dateMap[t.date].push(t);
    });

    return Object.keys(dateMap).sort().map((date, idx) => ({
      dateStr: date,
      num: idx + 1,
      tasks: dateMap[date]
    }));
  };

  const calendarDays = getCalendarDays();

  if (loading) {
    return (
      <div className="page-container">
        <Skeleton height="36px" width="200px" />
        <Skeleton height="200px" style={{ marginTop: '24px' }} />
      </div>
    );
  }

  return (
    <div className="page-container wide">
      <div className="page-header">
        <h2 className="page-header-title">Study Planner</h2>
        <p className="page-header-sub">Generate and track an AI-optimised study schedule based on your exam dates.</p>
      </div>

      {!schedulePlan ? (
        <form className="schedule-form-card" onSubmit={handleGenerate}>
          <div className="form-section">
            <h3 className="form-section-title">
              <CalendarIcon size={16} /> Exam Details
            </h3>
            <div className="form-group">
              <label className="form-label">Target Exam Date</label>
              <input
                className="form-input"
                type="date"
                required
                value={formData.examDate}
                onChange={(e) => setFormData({ ...formData, examDate: e.target.value })}
              />
            </div>
            <div className="form-group">
              <label className="form-label">Study Hours per Day</label>
              <div className="range-container">
                <input
                  type="range" min="1" max="14" step="1"
                  value={formData.studyHoursPerDay}
                  onChange={(e) => setFormData({ ...formData, studyHoursPerDay: e.target.value })}
                />
                <span className="range-value">{formData.studyHoursPerDay} hrs</span>
              </div>
            </div>
          </div>

          <div className="form-section">
            <h3 className="form-section-title">
              <Book size={16} /> Subjects
            </h3>
            <div className="subjects-list">
              {formData.subjects.map((sub, idx) => (
                <div key={idx} className="subject-row">
                  <input
                    className="form-input"
                    type="text"
                    placeholder="Subject name"
                    required
                    value={sub.name}
                    onChange={(e) => handleSubjectChange(idx, 'name', e.target.value)}
                  />
                  <select
                    className="form-select"
                    value={sub.weight}
                    onChange={(e) => handleSubjectChange(idx, 'weight', e.target.value)}
                  >
                    <option value="High">High Priority</option>
                    <option value="Medium">Medium Priority</option>
                    <option value="Low">Low Priority</option>
                  </select>
                  {formData.subjects.length > 1 && (
                    <button type="button" className="remove-btn" onClick={() => removeSubject(idx)} aria-label="Remove subject">
                      <Trash2 size={16} />
                    </button>
                  )}
                </div>
              ))}
            </div>
            <div style={{ marginTop: '0.75rem' }}>
              <Button type="button" variant="outline" onClick={addSubject}>
                <Plus size={15} style={{ marginRight: '4px' }} /> Add Subject
              </Button>
            </div>
          </div>

          <div className="form-actions">
            <Button type="submit" variant="primary" isLoading={isGenerating}>
              Generate Study Schedule
            </Button>
          </div>
        </form>
      ) : (
        <div className="schedule-layout-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 300px', gap: '1.5rem' }}>
          {/* Calendar Grid View */}
          <div className="calendar-view">
            <div className="calendar-view-header">
              <div>
                <p className="page-header-title" style={{ fontSize: '1rem' }}>Study Calendar</p>
                <p className="page-header-sub">
                  Target: {schedulePlan.studyHoursPerDay} hours/day · Exam on {schedulePlan.examDate || '—'}
                </p>
              </div>
              <Button variant="outline" onClick={() => setSchedulePlan(null)}>
                Reset Plan
              </Button>
            </div>

            <div className="calendar-grid" style={{ gridTemplateColumns: 'repeat(7, 1fr)' }}>
              {weekDays.map(day => (
                <div key={day} className="calendar-day-header">{day}</div>
              ))}
              {calendarDays.map((day) => {
                const isSelected = day.dateStr === selectedDateStr;
                return (
                  <div
                    key={day.dateStr}
                    className={`calendar-cell ${isSelected ? 'selected' : ''}`}
                    onClick={() => showTasksForDate(schedulePlan.tasks, day.dateStr)}
                    style={{
                      cursor: 'pointer',
                      border: isSelected ? '2px solid var(--primary)' : '1px solid var(--border-color)',
                      transition: 'all 0.15s ease'
                    }}
                  >
                    <span className="date-num" style={{ color: isSelected ? 'var(--primary)' : 'var(--text-muted)' }}>
                      Day {day.num}
                    </span>
                    <div className="task-pills-wrap" style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
                      {day.tasks.slice(0, 2).map((task) => (
                        <span
                          key={task.id}
                          className={`task-pill ${task.completed ? 'green' : 'blue'}`}
                          style={{
                            textDecoration: task.completed ? 'line-through' : 'none',
                            fontSize: '0.625rem',
                            padding: '1px 4px',
                            display: 'flex',
                            alignItems: 'center',
                            gap: '2px'
                          }}
                        >
                          {task.completed && <Check size={8} />} {task.subject.substring(0, 8)}
                        </span>
                      ))}
                      {day.tasks.length > 2 && (
                        <span className="task-pill slate" style={{ fontSize: '0.55rem', padding: '0 2px' }}>
                          +{day.tasks.length - 2} more
                        </span>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Daily tasks & Reschedule panel */}
          <div className="feature-card" style={{ height: 'fit-content' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '12px' }}>
              <CalendarDays size={18} className="success" />
              <p className="section-label" style={{ margin: 0 }}>
                Tasks: {selectedDateStr ? new Date(selectedDateStr).toLocaleDateString() : 'Select Day'}
              </p>
            </div>

            {selectedDayTasks.length === 0 ? (
              <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>No tasks scheduled for this day.</p>
            ) : (
              <div className="daily-task-list" style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {selectedDayTasks.map((task) => (
                  <div
                    key={task.id}
                    className="daily-task-item"
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      padding: '8px 10px',
                      borderRadius: 'var(--radius-md)',
                      border: '1px solid var(--border-color)',
                      backgroundColor: 'var(--bg-color)'
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <button
                        onClick={() => handleToggleTask(task.id)}
                        style={{
                          height: '18px',
                          width: '18px',
                          borderRadius: '4px',
                          border: '1px solid var(--border-color)',
                          backgroundColor: task.completed ? 'var(--success)' : 'var(--surface-color)',
                          color: '#fff',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          cursor: 'pointer'
                        }}
                      >
                        {task.completed && <Check size={12} />}
                      </button>
                      <div>
                        <p
                          style={{
                            fontSize: '0.875rem',
                            fontWeight: 600,
                            margin: 0,
                            textDecoration: task.completed ? 'line-through' : 'none',
                            color: task.completed ? 'var(--text-muted)' : 'var(--text-main)'
                          }}
                        >
                          {task.subject}
                        </p>
                        <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', margin: 0, display: 'flex', alignItems: 'center', gap: '4px' }}>
                          <Clock size={10} /> {task.hours} hours · {task.type}
                        </p>
                      </div>
                    </div>

                    <button
                      className="remove-btn"
                      onClick={() => startReschedule(task)}
                      title="Reschedule task"
                      aria-label="Reschedule task"
                      style={{ padding: '4px' }}
                    >
                      <RefreshCw size={13} />
                    </button>
                  </div>
                ))}
              </div>
            )}

            {/* Rescheduling Form */}
            {reschedulingTask && (
              <div
                className="reschedule-modal-overlay"
                style={{
                  marginTop: '16px',
                  paddingTop: '16px',
                  borderTop: '1px solid var(--border-color)'
                }}
              >
                <p style={{ fontSize: '0.8125rem', fontWeight: 600, margin: '0 0 8px 0' }}>
                  Reschedule: {reschedulingTask.subject}
                </p>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <input
                    type="date"
                    className="form-input"
                    value={newDate}
                    onChange={(e) => setNewDate(e.target.value)}
                    style={{ flex: 1, height: '32px' }}
                  />
                  <Button variant="primary" size="sm" onClick={handleRescheduleSubmit} style={{ height: '32px' }}>
                    Move
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setReschedulingTask(null)} style={{ height: '32px' }}>
                    X
                  </Button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default Schedule;